platform :osx, '10.11'
use_frameworks!

target 'Postcard' do

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/OperatorFoundation/OperatorPods'

pod 'GoogleAPIClientForREST/People'
pod 'GoogleAPIClientForREST/Gmail', '~> 1.1.1'
pod 'GTMOAuth2', '~> 1.1.4'
pod 'Sodium', :git => 'https://github.com/jedisct1/swift-sodium.git'
pod 'mailcore2-osx'
pod 'SAMKeychain'

end

target 'PostcardTests' do

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/OperatorFoundation/OperatorPods'

pod 'GoogleAPIClientForREST/People'
pod 'GoogleAPIClientForREST/Gmail', '~> 1.1.1'
pod 'GTMOAuth2', '~> 1.1.4'
pod 'Sodium', :git => 'https://github.com/jedisct1/swift-sodium.git'
pod 'mailcore2-osx'
pod 'SAMKeychain'

end

target 'PostcardUITests' do

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/OperatorFoundation/OperatorPods'

pod 'GoogleAPIClientForREST/People'
pod 'GoogleAPIClientForREST/Gmail', '~> 1.1.1'
pod 'GTMOAuth2', '~> 1.1.4'
pod 'Sodium', :git => 'https://github.com/jedisct1/swift-sodium.git'
pod 'mailcore2-osx'
pod 'SAMKeychain'

end

